#baseURL = 'https://3ml.org.uk/'
languageCode = 'en-gb'
title = '3ml - Three Minute Learning'

[params]
  description = "Improving literacy and science learning in schools"
  # Set HUGO_PARAMS_cdn to override
  # e.g. HUGO_PARAMS_cdn=https://somewhereonline.blah
  cdn = ""

[menu]
[[menu.main]]
  id = "resources"
  name = "Resources"
  pageRef = "/resources"
  weight = 30
