#! /bin/bash

NAME=$1
IMG_URL=$2
IMG_ALT=$3
URL=$4


cat<<EOF
<a href="$URL" target="_blank" rel="noopener noreferrer" class="w-full lg:w-1/2 text-md hover:text-tml-blue">
    <div class="flex items-center w-full lg:w-11/12 lg:mx-auto bg-white p-6 shadow-md hover:shadow-xl mb-8">
        <div class="w-32 h-32 flex-none mr-3 sm:mr-5">
            <img class="object-center object-contain h-32 rounded" src="$IMG_URL" alt="$IMG_ALT">
        </div>
        <div class="text-center">
            <h2 class="text-lg">$NAME</h2>
        </div>
    </div>
</a>
EOF
