#!/bin/bash

TITLE=$1
FILE=$2

cat << EOF
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>$TITLE</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="app.css">
  <link rel="icon" type="image/png" href="/img/icon.png">
</head>
<body>
$(<$FILE)
</body>
</html>
EOF
