#!/bin/bash

TITLE=$1
FILE=$2

cat << EOF
<!DOCTYPE html>
<head>
  <meta charset="UTF-8">
  <title>$TITLE</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="3ml-static.css">
  <link rel="icon" type="image/png" href="https://3ml.org.uk/img/icon.png">
</head>
<body class="min-h-screen flex flex-col">
<nav class="print:none bg-tml-blue mb-4">
  <div class="container px-2 py-2 mx-auto flex items-center justify-between flex-wrap">
    <div class="flex items-center flex-shrink-0 mr-8">
      <img class="fill-current" src="https://3ml.org.uk/img/logo.png" alt="The Three Minute Learning logo (3ml)">
    </div>
    <input id="menu-toggle" type="checkbox" class="hidden">
    <div class="block md:hidden">
      <label for="menu-toggle" class="flex items-center px-3 py-2 border rounded">
        <svg class="fill-current text-white h-3 w-3" viewBox="0 0 20 20"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"></path></svg>
      </label>
    </div>
    <div class="menu w-full flex-grow md:flex md:items-center md:w-auto">
      <div class="text-base md:flex-grow">
        <a class="block mt-4 md:inline-block md:mt-0 text-teal-100 hover:text-white mr-4" href="index.html">Home</a>
        <a class="block mt-4 md:inline-block md:mt-0 text-teal-100 hover:text-white mr-4" href="about.html">About</a>
        <a class="block mt-4 md:inline-block md:mt-0 text-teal-100 hover:text-white mr-4" href="guidance.html">Guidance</a>
        <a class="block mt-4 md:inline-block md:mt-0 text-teal-100 hover:text-white mr-4" href="researchers.html">Resources</a>
        <a class="block mt-4 md:inline-block md:mt-0 text-teal-100 hover:text-white mr-4" href="https://3ml.org.uk/app/#/login" target="_blank">Sign in</a>
        <a class="block mt-4 md:inline-block md:mt-0 text-teal-100 hover:text-white mr-4" href="https://3ml.org.uk/app/#/register" target="_blank">Sign up</a>
      </div>
    </div>
  </div>
</nav>
<div class="container mx-auto px-2 bg-gray-100 mb-4">
$(envsubst<$FILE)
</div>
<div class="flex-1"></div>
$(<footer.html)
</body>
</html>
EOF
