#! /bin/bash

NAME=$1
IMG_URL=$2
URL=$3
BLURB=$4

cat<<EOF
<a href="$URL" target="_blank" rel="noopener noreferrer" class="w-full md:w-1/2 text-md hover:text-tml-blue">
    <div class="flex w-full md:w-11/12 md:mx-auto h-40 md:h-48 bg-white p-6 shadow-md mb-8">
      <div class="w-30 h-30 flex-none mr-3 sm:mr-5">
        <img class="rounded" src="$IMG_URL" alt="$NAME">
      </div>
      <div class="text-left">
        <h2 class="text-lg">$NAME</h2>
        <p class="text-sm text-gray-700 block">$BLURB</p>
      </div>
    </div>
</a>
EOF
